// ENUM_Natures::NewEnumerator0 hardy
// 1 lonely
// 2 brave
// 3 adamant
// 4 naughty
// 5 bold
// ENUM_Natures::NewEnumerator6 docile
// ENUM_Natures::NewEnumerator7 relaxed
// 8 impish
// 9 lax
// ENUM_Natures::NewEnumerator10 timid
// 11 hasty
// ENUM_Natures::NewEnumerator12 serious
// 13 jolly
// 14 naive
// 15 modest
// ENUM_Natures::NewEnumerator16 mild
// ENUM_Natures::NewEnumerator17 quiet
// 18 bashful
// 19 rash
// 20 calm
// 21 gentle
// 22 sassy
// 23 careful
// ENUM_Natures::NewEnumerator24 quirky

pub fn get_nature_from_enum(enum_str: &str) -> Option<&str> {
    match enum_str {
        "ENUM_Natures::NewEnumerator0" => Some("hardy"),
        "ENUM_Natures::NewEnumerator1" => Some("lonely"),
        "ENUM_Natures::NewEnumerator2" => Some("brave"),
        "ENUM_Natures::NewEnumerator3" => Some("adamant"),
        "ENUM_Natures::NewEnumerator4" => Some("naughty"),
        "ENUM_Natures::NewEnumerator5" => Some("bold"),
        "ENUM_Natures::NewEnumerator6" => Some("docile"),
        "ENUM_Natures::NewEnumerator7" => Some("relaxed"),
        "ENUM_Natures::NewEnumerator8" => Some("impish"),
        "ENUM_Natures::NewEnumerator9" => Some("lax"),
        "ENUM_Natures::NewEnumerator10" => Some("timid"),
        "ENUM_Natures::NewEnumerator11" => Some("hasty"),
        "ENUM_Natures::NewEnumerator12" => Some("serious"),
        "ENUM_Natures::NewEnumerator13" => Some("jolly"),
        "ENUM_Natures::NewEnumerator14" => Some("naive"),
        "ENUM_Natures::NewEnumerator15" => Some("modest"),
        "ENUM_Natures::NewEnumerator16" => Some("mild"),
        "ENUM_Natures::NewEnumerator17" => Some("quiet"),
        "ENUM_Natures::NewEnumerator18" => Some("bashful"),
        "ENUM_Natures::NewEnumerator19" => Some("rash"),
        "ENUM_Natures::NewEnumerator20" => Some("calm"),
        "ENUM_Natures::NewEnumerator21" => Some("gentle"),
        "ENUM_Natures::NewEnumerator22" => Some("sassy"),
        "ENUM_Natures::NewEnumerator23" => Some("careful"),
        "ENUM_Natures::NewEnumerator24" => Some("quirky"),
        _ => None,
    }
}
